export const ABOUT = "/about"
export const CART = "/cart"
export const ORDER_SUMMARY = "/checkout/order-summary"
export const SHIPPING = "/checkout/shipping"
export const PAYMENT = "/checkout/payment"
export const CURRENT_CUSTOMER = "/users/current-customer"
export const CURRENT_ADMIN = "/users/current-admin"
export const FAQ = "/faq"
export const HOME = "/"
export const NOT_FOUND = "*"
export const LOGIN = "/login"
export const PRODUCTS = "/products"
export const SHOP_QUERY_CATEGORY_PREFIX = "/shop?category="
export const SIGN_UP = "/sign-up"
export const SIGN_UP_ADMIN = "/sign-up-admin"
export const SHOP = "/shop"
export const WITHOUT_NAVBAR = [LOGIN, SIGN_UP, SIGN_UP_ADMIN]
